
# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: cinoliu
url: http://cinoliu.github.io
feed: /atom.xml
author_info: <a href="http://cinoliu.github.io/">cinoliu</a>

myblog:
  gavatar: images/2.jpg
  gpname: cinoliu
  linkedin: http://www.linkedin.com/in/cinoliu
  email: mailto:zongyu.liu@foxmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books ,test]
